// @ts-check
// Leveraged ETF families for the Tools finder and price target.
// curated map: underlying → [symbol, daily leverage factor], longs first.
// Leverage labels are static (issuers do change them); prices/volume/spread come live from quotes.

/** @type {Record<string, [string, number][]>} */
export const LEV_ETFS = {
  // indexes / sectors / commodities
  SPY:  [['SSO',2],['UPRO',3],['SPXL',3],['SH',-1],['SDS',-2],['SPXU',-3],['SPXS',-3]],
  QQQ:  [['QLD',2],['TQQQ',3],['PSQ',-1],['QID',-2],['SQQQ',-3]],
  IWM:  [['UWM',2],['TNA',3],['RWM',-1],['TWM',-2],['TZA',-3]],
  DIA:  [['DDM',2],['UDOW',3],['DOG',-1],['DXD',-2],['SDOW',-3]],
  SMH:  [['USD',2],['SOXL',3],['SSG',-2],['SOXS',-3]],
  MAGS: [['MAGX',2],['MAGQ',-1]],
  ARKK: [['TARK',2],['SARK',-1]],
  XLK:  [['TECL',3],['TECS',-3]],
  XLF:  [['FAS',3],['FAZ',-3]],
  XLE:  [['ERX',2],['ERY',-2]],
  XLV:  [['CURE',3]],
  XLRE: [['DRN',3],['DRV',-3]],
  XOP:  [['GUSH',2],['DRIP',-2]],
  XBI:  [['LABU',3],['LABD',-3]],
  KRE:  [['DPST',3]],
  ITB:  [['NAIL',3]],
  EEM:  [['EDC',3],['EDZ',-3]],
  FXI:  [['YINN',3],['YANG',-3]],
  KWEB: [['CWEB',2]],
  TLT:  [['UBT',2],['TMF',3],['TBF',-1],['TBT',-2],['TMV',-3]],
  GLD:  [['UGL',2],['GLL',-2]],
  SLV:  [['AGQ',2],['ZSL',-2]],
  USO:  [['UCO',2],['SCO',-2]],
  UNG:  [['BOIL',2],['KOLD',-2]],
  GDX:  [['NUGT',2],['DUST',-2]],
  GDXJ: [['JNUG',2],['JDST',-2]],
  VIX:  [['UVIX',2],['UVXY',1.5],['SVIX',-1],['SVXY',-0.5]],
  // crypto
  IBIT: [['BITX',2],['BITU',2],['BTCL',2],['BITI',-1],['SBIT',-2],['BTCZ',-2]],
  ETHA: [['ETHU',2],['ETHT',2],['ETU',2],['SETH',-1],['ETHD',-2]],
  SOL:  [['SLON',2],['SOLT',2]],
  XRP:  [['UXRP',2],['XRPT',2]],
  ADA:  [['CRDX',2]],
  XLM:  [['STLU',2]],
  LINK: [['CHNU',2]],
  // single stocks
  NVDA: [['NVDL',2],['NVDU',2],['NVDX',2],['NVDG',2],['NVDB',2],['NVC',2],['NVDD',-1],['NVDS',-1.5],['NVD',-2],['NVDQ',-2]],
  TSLA: [['TSLL',2],['TSLT',2],['TSLR',2],['TSLG',2],['TSLI',2],['TESC',2],['TSL',1.25],['TSLS',-1],['TSLQ',-2],['TSLZ',-2],['TSDD',-2]],
  AAPL: [['AAPU',2],['AAPB',2],['AAPX',2],['IOSX',2],['AAPD',-1]],
  MSFT: [['MSFU',2],['MSFL',2],['MSFX',2],['MSFC',2],['MSFD',-1]],
  AMZN: [['AMZU',2],['AMZZ',2],['AMAA',2],['AMZD',-1],['AMZO',-2]],
  GOOGL:[['GGLL',2],['GOU',2],['GOOX',2],['GOGL',2],['GGLS',-1]],
  META: [['METU',2],['FBL',2],['FBX',2],['METD',-1]],
  AMD:  [['AMDL',2],['AMUU',2],['AMDC',2],['AMDD',-1],['DAMD',-2]],
  AVGO: [['AVL',2],['AVGU',2],['AVGX',2],['AVGC',2],['AVS',-1]],
  NFLX: [['NFXL',2],['NFLU',2],['NFX',2],['NFXS',-1]],
  MU:   [['MUU',2],['MULL',2],['MIC',2],['MUD',-1]],
  TSM:  [['TSMX',2],['TSMU',2],['TWSC',2],['TSMZ',-1]],
  COIN: [['CONL',2],['CONX',2],['COIA',2],['COIX',2],['CONI',-2]],
  MSTR: [['MSTU',2],['MSTX',2],['MSTP',2],['MSTC',2],['MSTZ',-2],['SMST',-2]],
  PLTR: [['PLTU',2],['PTIR',2],['PLTG',2],['PLTA',2],['PLTL',2],['PLTD',-1]],
  SMCI: [['SMCX',2],['SMCL',2],['SMCC',2],['SMCZ',-2]],
  BABA: [['BABX',2],['BABU',2]],
  SKHY: [['SKUU',2],['SKHA',2],['SKHU',2],['SKHX',2],['SKHL',2],['HYNX',2],['SK',2],['SKHZ',-1],['SKDD',-2],['SKHN',-2]],
  SPCX: [['SPCM',2],['SPAL',2],['LOFF',2],['SPCF',2],['SPAX',2],['SPCU',2],['SPCG',-2],['SNK',-2],['LOFD',-2],['SPCQ',-2]],
  HOOD: [['ROBN',2],['HOOX',2],['HOOG',2],['HODU',2],['HOOZ',-2]],
  ORCL: [['ORCX',2],['ORCU',2],['ORAC',2],['ORCS',-1],['ORCZ',-2]],
  CRCL: [['CRCG',2],['CRCA',2],['CCUP',2],['CRCD',-2]],
  BE:   [['BEX',2],['BEG',2],['BEC',2],['BEZ',-2]],
  SMR:  [['SMUP',2],['SMU',2],['SMZ',-2]],
  SOFI: [['SOFX',2],['SOFA',2]],
  APP:  [['APPX',2],['APPC',2]],
  INTC: [['LINT',2],['INTW',2],['INT',2]],
  ASML: [['ASMU',2],['ASMG',2],['ASMZ',2]],
  MRVL: [['MRVU',2],['MVLL',2],['MRVX',2]],
  PYPL: [['PYPU',2],['PYPG',2]],
  UNH:  [['UNHU',2],['UNHG',2],['UN',2]],
  QCOM: [['QCMU',2],['QCML',2],['QCMD',-1]],
  PANW: [['PALU',2],['PALD',-1]],
  CSCO: [['CSCL',2],['CSCS',-1]],
  NBIS: [['NBIL',2],['NEBX',2],['NBIZ',-2]],
  SNDK: [['SNDU',2],['SNXX',2],['SNDC',2],['SNDQ',-2]],
  AXTI: [['AXTU',2],['AXTX',2],['AXTC',2]],
  CRWV: [['CRWU',2],['CRWX',2],['CORD',-2]],
  AAOI: [['AAOX',2],['AAOZ',-2]],
  APLD: [['APLX',2],['APLZ',-2]],
  LITE: [['LITX',2],['LITZ',-2]],
  CBRS: [['CBRG',2],['CBRZ',-2]],
  IREN: [['IREZ',-2]],
  HIMS: [['HIMZ',2],['HIMD',-2]],
  RKLB: [['RKLX',2],['RKX',2],['RKLZ',-2]],
  IONQ: [['IONX',2],['IONL',2],['IONC',2],['IONZ',-2]],
  OKLO: [['OKLL',2],['OKLS',-2]],
  SOUN: [['SOUX',2]],
  RDDT: [['RDTL',2]],
  CRWD: [['CRWL',2]],
  SNOW: [['SNOU',2]],
  GME:  [['GMEU',2],['GMEC',2]],
  MARA: [['MRAL',2]],
  AFRM: [['AFRU',2]],
  AXON: [['AXUP',2]],
  KTOS: [['KTUP',2]],
  CLS:  [['CSEX',2]],
  NNE:  [['NNEX',2]],
  SNPS: [['SNPX',2]],
  RCAT: [['RCAX',2]],
  POET: [['POEL',2]],
  BTDR: [['BTDL',2]],
  CRML: [['CRMU',2]],
  ARM:  [['ARMG',2],['ARMA',2]],
  DELL: [['DLLL',2]],
  RBLX: [['RBLU',2]],
  DJT:  [['DJTU',2]],
  LLY:  [['ELIL',2],['LLYX',2],['LLYZ',-2]],
  BRKB: [['BRKU',2]],
  XOM:  [['XOMX',2]],
  BA:   [['BOEU',2]],
  SHOP: [['SHPU',2]],
  LMT:  [['LMTL',2]],
  ADBE: [['ADBU',2]],
  TXN:  [['TXNU',2]],
  BB:   [['BBUL',2]],
  ISRG: [['ISUL',2]],
  NOW:  [['NOWL',2],['NOWX',2]],
  NTAP: [['NTAL',2]],
  PDD:  [['PDDL',2]],
  RIVN: [['RVNL',2]],
  TDC:  [['TDCL',2]],
  UBER: [['UBRL',2]],
  VRT:  [['VRTL',2]],
  P:    [['PUL',2]],
  TTD:  [['TTDU',2]],
  GLXY: [['GLXU',2],['GLX',2]],
  BMNR: [['BMNU',2],['BMNX',2],['BNMC',2],['BMNZ',-2]],
  SBET: [['SBTU',2]],
  CIFR: [['CIFU',2],['CIFC',2]],
  EOSE: [['EOSU',2],['EO',2]],
  RDW:  [['RDWU',2]],
  FIGR: [['FGRU',2]],
  APH:  [['APHU',2]],
  PAAS: [['PAAU',2]],
  HL:   [['HLXX',2]],
  IBM:  [['IBX',2]],
  WULF: [['WULX',2]],
  JOBY: [['JOBX',2]],
  OPEN: [['OPEX',2]],
  ONDS: [['ONDU',2]],
  ASTS: [['ASTX',2],['ASTT',2]],
  ACHR: [['ARCX',2],['ACHX',2]],
  LEU:  [['LEUX',2]],
  UPST: [['UPSX',2]],
  ENPH: [['ENPX',2]],
  WDC:  [['WDCX',2]],
  DDOG: [['DOGD',2]],
  ALAB: [['LABX',2]],
  XYZ:  [['XYZG',2]],
  CRM:  [['CRMG',2]],
  AAL:  [['AALG',2]],
  UEC:  [['UECG',2]],
  CDNS: [['CDNG',2]],
  GEV:  [['GEVG',2]],
  STX:  [['STXU',2]],
  TER:  [['TERG',2]],
  ON:   [['ONG',2]],
  SPOT: [['SPOG',2]],
  CVNA: [['CVNX',2]],
  RGTI: [['RGTX',2]],
  B:    [['BU',2]],
  INFQ: [['INFH',2]],
  ACLS: [['ACLZ',2]],
  ACMR: [['ACMM',2]],
  CAMT: [['CAMC',2]],
  CRUS: [['CRUC',2]],
  LASR: [['LASC',2]],
  LRN:  [['LRNX',2]],
  MNST: [['MNSX',2]],
  SIMO: [['SIMX',2]],
  UMC:  [['UMCX',2]],
  CART: [['CARX',2]],
  MSI:  [['MSIX',2]],
  ONTO: [['ONTX',2]],
  RMBS: [['RMBC',2]],
  TPL:  [['TPLX',2]],
  KEYS: [['KEYX',2]],
  UCTT: [['UCTX',2]],
  COHR: [['COHC',2]],
  AMAT: [['APMI',2]],
  LRCX: [['LRCC',2]],
};

/** @type {Record<string, string>} */
export const LEV_NAMES = {
  SPY: 'S&P 500', QQQ: 'Nasdaq 100', IWM: 'Russell 2000', DIA: 'Dow 30', SMH: 'semiconductors',
  MAGS: 'Mag 7', ARKK: 'ARK Innovation', XLK: 'tech sector', XLF: 'financials', XLE: 'energy',
  XLV: 'healthcare', XLRE: 'real estate', XOP: 'oil & gas E&P', XBI: 'biotech', KRE: 'regional banks',
  ITB: 'homebuilders', EEM: 'emerging markets', FXI: 'China large caps', KWEB: 'China internet',
  TLT: '20+ yr treasuries', GLD: 'gold', SLV: 'silver', USO: 'WTI crude', UNG: 'nat gas',
  GDX: 'gold miners', GDXJ: 'junior gold miners', VIX: 'VIX futures',
  IBIT: 'bitcoin', ETHA: 'ether', SOL: 'solana', ADA: 'cardano', XLM: 'stellar', LINK: 'chainlink',
  SKHY: 'SK Hynix', SPCX: 'SpaceX', BRKB: 'Berkshire B', P: 'Everpure', B: 'Barrick', INFQ: 'Infleqtion', CART: 'Instacart', LRN: 'Stride', LASR: 'nLIGHT',
};

/** @type {Record<string, string>} */
export const LEV_ALIASES = {
  SPX: 'SPY', ES: 'SPY', VOO: 'SPY', IVV: 'SPY', SPLG: 'SPY',
  NDX: 'QQQ', NQ: 'QQQ', QQQM: 'QQQ',
  RUT: 'IWM', RTY: 'IWM', DJI: 'DIA', DJX: 'DIA', YM: 'DIA', SOXX: 'SMH',
  GOOG: 'GOOGL', BTC: 'IBIT', BITO: 'IBIT', GBTC: 'IBIT', FBTC: 'IBIT',
  ETH: 'ETHA', ETHE: 'ETHA', ETHW: 'ETHA', HYNIX: 'SKHY', SPACEX: 'SPCX',
  BRK: 'BRKB', SOLANA: 'SOL',
};

// typing a leveraged symbol itself resolves to its family (TQQQ → the QQQ set)

/** @type {Record<string, { under: string, lev: number }>} */
export const LEV_REVERSE = {};

for (const [u, list] of Object.entries(LEV_ETFS)) for (const [s, l] of list) LEV_REVERSE[s] = { under: u, lev: l };
